version: '3.10'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - PORT=3000
      - ENV=prod
    command: pc run --env prod
    working_dir: /app
    user: pynecone
